### ISSUE TITLE
Consider addition of ISNI as an identifier for organizations

### ISSUE THREAD

**Issue by mconlon17** [openrif/community#14]
ISNI, the International Standard Name identifier has been issued to over 446K organizations world wide.  The University of Florida ISNI, for example, is 0000 0004 1936 8091.  UF has extended its VIVO to allow for the capture of organizational ISNI.  Seems this should be a standard part of VIVO-ISF.

**Comment by gneissone** [comment]
Related session at the VIVO conference: The Complexity of Scholar Affiliation in ISNI and VIVO - Jing Wang, Karen Smith-Yoshimura and Janifer Gatenby. 

Just added ISNI to our local ontology for kicks.

**Comment by mconlon17** [comment]
Closing here.  Opening here:  https://github.com/openrif/vivo-isf-ontology/issues/713
