### ISSUE TITLE
Add domain and range to vivo:middleName

### ISSUE THREAD

**Issue by gneissone** [openrif/community#15]
vcard:givenName and vcard:familyName both have a domain of vcard:Name. vivo:middleName does not. This makes it impossible to add a middle name to a vcard:Name in the VIVO web interface unless you specify the domain manually (or edit the name via a foaf:person editing page). Should the following domain and range be added to vivo:middleName in the ontology?

```
    <rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#string"/>
    <rdfs:domain rdf:resource="http://www.w3.org/2006/vcard/ns#Name"/>
```

**Comment by mconlon17** [comment]
Closing here.  Opening https://github.com/openrif/vivo-isf-ontology/issues/712
