### ISSUE TITLE
vivo:dateFiled  (domain: biboPatent)

### ISSUE THREAD

**Issue by mjaved495** [openrif/community#21]
The domain of the property vivo:dateFiled is defined as bibo:Patent.
1. My understanding on this property is that it is equivalent to "date submitted".
2. I think the domain of such a generalized property should be either kept "open" (i.e., without a domain) or a very higher-level class should be defined as its domain e.g. (obo:IAO_0000030 - Information Content Entity).

**Comment by arademaker** [comment]
In that case, I would suggest make its domain the Patent.

**Comment by mconlon17** [comment]
Closing here.  Opening https://github.com/openrif/vivo-isf-ontology/issues/711
