### ISSUE TITLE
Virustotal via Proxy from Corporate

### ISSUE THREAD

**Issue by satmit** [openrif/community#26]
Hi Team,

I need to enable proxy to access the Virustotal module in Cuckoo. Now I have installed Cukoo in RHEL 7.

Where I need to provide Proxy to enable VT module in Cuckoo.?

Note: I tried using proxy in Browser, but it doesn't work.

Thank You.!

SatheeshKumar T

**Comment by marijane** [comment]
Did you mean to open this at https://github.com/cuckoosandbox/cuckoo/issues?
