### ISSUE TITLE
hasCollaborator property doesn't have inverse

### ISSUE THREAD

**Issue by arademaker** [openrif/community#3]
The property http://vivoweb.org/ontology/core#hasCollaborator doesn't have a inverse property. Is that the original idea or a bug? The property does not have any documentation that describes its intentional meaning either. 

Another possible suggestion is to make this property reflexive.

**Comment by mconlon17** [comment]
Closing here.  Opening here:  https://github.com/openrif/vivo-isf-ontology/issues/716
