### ISSUE TITLE
Incorporate the contribution ontology in VIVO-ISF

### ISSUE THREAD

**Issue by mconlon17** [openrif/community#37]
Unclear what is involved here.  The ontology is provided in OpenVIVO in a separate tbox filegraph.

Ontology needs to be at OBO? The URL used in OpenVIVO does not resolve:

http://purl.obolibrary.org/obo/cro.owl

Then can be treated as an independent ontology in VIVO, separately loadable, separately referenced in SPARQL?

**Comment by marijane** [comment]
Right now the plan is to release a file with the CRO as a standalone ontology and a bridge file to connect it to VIVO-ISF.

Registering the purl is on my to-do list.

**Comment by marijane** [comment]
PURL request is at https://github.com/OBOFoundry/OBOFoundry.github.io/issues/355

The contribution ontology is being refactored to adhere more closely to the CRediT taxonomy, and implemented according to OBO principles.  New repository is at https://github.com/openrif/contributor-role-ontology.

**Comment by mconlon17** [comment]
Understood.  Closing as won't do.
