### ISSUE TITLE
Ontology 7.1 and 8.4 compatibility

### ISSUE THREAD

**Issue by Anukshuk** [openrif/community#48]
I downloaded Ontology app 7.1 to connect with my Ledger Nano S. After a bit I downloaded the newer version 8.4. I  am unable to see my Tokens on the newer app after I conncet with it. I could do it a few times but it didn't work after a couple of days. So I was forced to go back and use my older version whic works. 
Can someone please help me resolve this issue. i would really appreciate it.
Thanks.

**Comment by marijane** [comment]
@Anukshuk,

I am afraid you are in the wrong place to seek help.  This repository is for discussion of the VIVO Integrated Semantic Framework, an OWL Ontology used for describing scholarly research networks and the resources used in conducting scientific research, and used in the open source VIVO and eagle-i software platforms.  

It sounds like you are looking for support for the Ontology cryptocurrency project, which has a website at https://ont.io/.  You might also try the Ledger wallet support site at https://support.ledgerwallet.com/hc/en-us.

**Comment by marijane** [comment]
I think I found the Ontology project's GitHub site. https://github.com/ontio/documentation

This page looks like it may address your issue:
https://github.com/ontio/documentation/blob/master/walletDevDocs/How%20to%20install%20and%20use%20ONT.md
