### ISSUE TITLE
vivo:Report is too general -- need subclasses

### ISSUE THREAD

**Issue by jcorson55** [openrif/community#6]
Violeta @ the I-Fest - we need subclasses such as technical report, case report

**Comment by vioil** [comment]
Just a clarification why - at present we use bibo:report defined in NLM as technical report - "Technical Report: Work consisting of a formal report giving details of the investigation and results of a medical or other scientific problem. When issued by a government agency or comparable official body, its contents may be classified, unclassified, or declassified with regard to security clearance. This publication type may also cover a scientific paper or article that records the current state or current position of scientific research and development. If so labeled by the editor or publisher, this publication type may be properly used for journal articles."

We need few sub-classes of bibo:report: 
case report, deliverable report, meeting report, news report, technical report, trial report

**Comment by mconlon17** [comment]
Closing here.  Opening here:  https://github.com/openrif/vivo-isf-ontology/issues/717
